version: '3.8'

services:
  db:
    image: postgres
    container_name: nakama-postgres-container
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - nakama-network
  
volumes:
  db-data:

networks:
  nakama-network:
    driver: bridge
