version: '3.8'

services:
  db:
    image: postgres
    container_name: nakama-postgres-container
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - nakama-network
  
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    container_name: nakama-redis-container
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - nakama-network

  redis-commander:
    container_name: nakama-redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOST=redis
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - redis
    restart:
      unless-stopped
    networks:
      - nakama-network
  
volumes:
  db-data:

networks:
  nakama-network:
    driver: bridge
